version: "2"
services:
   shell:
      image: taf7lwappqystqp4u7wjsqkdc7dquw/hollowray
      volumes:
         - ./private:/var/private
         - ./store:/home/emory/.password-store
      environment:
         - GIT_URL=git@github.com:AFnRFCb7/lanterngold.git
   gitpush:
      image: taf7lwappqystqp4u7wjsqkdc7dquw/angrybeta
      volumes:
         - ./private:/var/private
         - ./store:/srv
      environment:
         - GIT_URL=git@github.com:AFnRFCb7/lanterngold.git

